os:
  - linux
  - osx

language: node_js

node_js:
  - '4'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8

script:
  - bash ./scripts/travis-build.sh

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
